services:
  - type: web
    name: llm-playground
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 300 --workers 3 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 